name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: Install Playwright Browsers
        run: npx --no playwright install --with-deps --only-shell
      - name: build production project
        run: npm run build
        if: always()
      - name: linting
        run: npm run lint
        if: always()
      - name: unit testing
        run: npm run test:unit
        if: always()
      - name: screenshot testing
        run: npm run test:ui:ci